// employee-management-react/src/Account/VerifyEmail.tsx
import { useState, useEffect } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import queryString from 'query-string';
import { accountService } from '../_Services/account.service';
import Typography from '@mui/material/Typography';
import Grid from '@mui/material/Grid';
import { Box, Container } from '@mui/material';
import { useAlertContext } from '../_Context/useAlertContext';

const VerifyEmail = () => {
    const EmailStatus = {
        Verifying: 'Verifying',
        Failed: 'Failed',
        Verified: 'Verified'
    }

    const navigate = useNavigate();

    //set alert message
    const { setAlert } = useAlertContext();

    const [emailStatus, setEmailStatus] = useState(EmailStatus.Verifying);

    useEffect(() => {
        // eslint-disable-next-line no-restricted-globals
        const { token } = queryString.parse(location.search);

        // remove token from url to prevent http referer leakage
        // eslint-disable-next-line no-restricted-globals
        navigate(location.pathname);

        accountService.verifyEmail(token)
            .then((response) => {
                setAlert({ type: 'success', message: response.message });
                setEmailStatus(EmailStatus.Verified)
            })
            .catch((error) => {
                setAlert({ type: 'error', message: error.message });
                setEmailStatus(EmailStatus.Failed);
            });
    }, []);

    function getBody() {
        switch (emailStatus) {
            case EmailStatus.Verifying:
                return <Typography variant="h3" align="center" margin="dense">
                    Verifying...
                </Typography>;
            case EmailStatus.Failed:
                return <Typography variant="h3" align="center" margin="dense">
                    Verification Failed!!
                </Typography>;
            case EmailStatus.Verified:
                return <Typography variant="h3" align="center" margin="dense">
                    Congratulations!! You have been successfully verified!!. <Link to="/"> Please click here to Login!!</Link>
                </Typography>;
        }
    }

    return (
        <Container maxWidth="md">
            <Grid container margin={5} spacing={5}>
                <Box px={5} py={5}>
                    <Typography variant="h1" align="center" margin="dense">
                        Verify Email
                    </Typography>
                    <Typography>{getBody()}</Typography>
                </Box>
            </Grid>
        </Container>
    )
}

export default VerifyEmail;

// EmployeeManagementSPA/src/app/account/verify-email/verify-email.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { first } from 'rxjs';
import { SnackbarType } from 'src/app/_Models/Snackbar';
import { AccountService } from 'src/app/_Services/account.service';
import { SnackbarService } from 'src/app/_Shared/snackbar.service';



@Component({
  selector: 'app-verify-email',
  templateUrl: './verify-email.component.html',
  styleUrls: ['./verify-email.component.css']
})
export class VerifyEmailComponent implements OnInit {

  VerifingEmail: boolean = true;
  VerifiedEmail: boolean = false;
  Failed: boolean = false;


  constructor(private route: ActivatedRoute,
    private router: Router,
    private account: AccountService,
    private snackbar: SnackbarService) { }

  ngOnInit() {
    const token = this.route.snapshot.queryParams['token'];
    // remove token from url to prevent http referer leakage
    this.router.navigate([], { relativeTo: this.route, replaceUrl: true });

    this.account.VerifyEmail(token)
      .pipe(first())
      .subscribe({
        next: () => {
          this.snackbar.showSnackbar('Verification successful', SnackbarType.Success);
          //this.router.navigate(['../login'], { relativeTo: this.route });
          this.VerifiedEmail = true;
          this.VerifingEmail = false;
        },
        error: () => {
          this.Failed = true;
          this.VerifingEmail = false;
        }
      });
  }
}

<mat-card-header>
    <mat-card-title>
        <div *ngIf="Failed == true">
            <h3> Oops!! Verification Failed!!</h3>
        </div>
    </mat-card-title>
    <mat-card-title>
        <div *ngIf="VerifingEmail == true">
            <h3> Verifying...</h3>
        </div>
    </mat-card-title>
    <div *ngIf="VerifiedEmail == true">
        <h3>
            <mat-card-title>
                <mat-icon>Done</mat-icon>
                Congratulations!! You have been successfully verified!!
            </mat-card-title>
            <a routerLink="">Please click here to Login Now!!</a>
        </h3>
    </div>

</mat-card-header>
